# Generated by Django 3.2.6 on 2023-08-19 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bill_item_workorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='item_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='item_no',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='rate',
        ),
        migrations.AddField(
            model_name='workorder',
            name='vendor',
            field=models.CharField(default='romana', max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=150)),
                ('item_name', models.CharField(max_length=150)),
                ('rate', models.FloatField(default=0)),
                ('wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.workorder')),
            ],
        ),
    ]
