# Generated by Django 3.2.6 on 2023-08-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20230819_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='wo',
            field=models.ManyToManyField(to='books.WorkOrder'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.workorderitem'),
        ),
    ]
