# Generated by Django 3.2.6 on 2023-08-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20230819_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='rate_type',
            field=models.CharField(choices=[('Work Order', 'Work Order'), ('CS', 'CS'), ('Rate', 'Rate')], default='Work Order', max_length=10),
        ),
    ]
