# Generated by Django 3.2.6 on 2023-08-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_workorder_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
